/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as BrassRouteImport } from './routes/brass'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ColoursRouteImport } from './routes/colours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CopperRouteImport } from './routes/copper'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NavratnaRouteImport } from './routes/navratna'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TrackRouteImport } from './routes/track'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as GemstonesIndexRouteImport } from './routes/gemstones/index'
import { Route as GemstonesSlugRouteImport } from './routes/gemstones/$slug'
import { Route as OrderCodeRouteImport } from './routes/order/$code'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as OwnerAdsRouteImport } from './routes/owner/ads'
import { Route as OwnerAppearanceRouteImport } from './routes/owner/appearance'
import { Route as OwnerAstrologyRouteImport } from './routes/owner/astrology'
import { Route as OwnerCategoriesRouteImport } from './routes/owner/categories'
import { Route as OwnerDiscountsRouteImport } from './routes/owner/discounts'
import { Route as OwnerEnquiriesRouteImport } from './routes/owner/enquiries'
import { Route as OwnerGstRouteImport } from './routes/owner/gst'
import { Route as OwnerLiveRouteImport } from './routes/owner/live'
import { Route as OwnerOrdersRouteImport } from './routes/owner/orders'
import { Route as OwnerPaymentsRouteImport } from './routes/owner/payments'
import { Route as OwnerPerformanceRouteImport } from './routes/owner/performance'
import { Route as OwnerPrintRouteImport } from './routes/owner/print'
import { Route as OwnerProductsRouteImport } from './routes/owner/products'
import { Route as OwnerReviewsRouteImport } from './routes/owner/reviews'
import { Route as OwnerSecurityRouteImport } from './routes/owner/security'
import { Route as OwnerSellingRouteImport } from './routes/owner/selling'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerSlidesRouteImport } from './routes/owner/slides'
import { Route as OwnerSocialRouteImport } from './routes/owner/social'
import { Route as OwnerUsersRouteImport } from './routes/owner/users'
import { Route as OwnerVendorsRouteImport } from './routes/owner/vendors'
import { Route as OwnerVisitorsRouteImport } from './routes/owner/visitors'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api/razorpay/webhook'
import { Route as OwnerBillsIndexRouteImport } from './routes/owner/bills/index'
import { Route as OwnerBillsIdRouteImport } from './routes/owner/bills/$id'
import { Route as OwnerBillsExpensesRouteImport } from './routes/owner/bills/expenses'
import { Route as OwnerBillsPurchaseRouteImport } from './routes/owner/bills/purchase'
import { Route as OwnerBillsRepairRouteImport } from './routes/owner/bills/repair'
import { Route as OwnerBillsReturnsRouteImport } from './routes/owner/bills/returns'
import { Route as OwnerBillsSaleRouteImport } from './routes/owner/bills/sale'
import { Route as OwnerBillsStockRouteImport } from './routes/owner/bills/stock'
import { Route as OwnerInventoryIndexRouteImport } from './routes/owner/inventory/index'
import { Route as OwnerInventoryAlertsRouteImport } from './routes/owner/inventory/alerts'
import { Route as OwnerInventoryLabelsRouteImport } from './routes/owner/inventory/labels'
import { Route as OwnerInventoryLedgerRouteImport } from './routes/owner/inventory/ledger'
import { Route as OwnerInventoryScanRouteImport } from './routes/owner/inventory/scan'
import { Route as OwnerInventoryStockRouteImport } from './routes/owner/inventory/stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const BrassRoute = BrassRouteImport.update({
  id: '/brass',
  path: '/brass',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ColoursRoute = ColoursRouteImport.update({
  id: '/colours',
  path: '/colours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CopperRoute = CopperRouteImport.update({
  id: '/copper',
  path: '/copper',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NavratnaRoute = NavratnaRouteImport.update({
  id: '/navratna',
  path: '/navratna',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GemstonesIndexRoute = GemstonesIndexRouteImport.update({
  id: '/gemstones/',
  path: '/gemstones/',
  getParentRoute: () => rootRouteImport,
} as any)
const GemstonesSlugRoute = GemstonesSlugRouteImport.update({
  id: '/gemstones/$slug',
  path: '/gemstones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAdsRoute = OwnerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAppearanceRoute = OwnerAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAstrologyRoute = OwnerAstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCategoriesRoute = OwnerCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDiscountsRoute = OwnerDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerEnquiriesRoute = OwnerEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGstRoute = OwnerGstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLiveRoute = OwnerLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPerformanceRoute = OwnerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPrintRoute = OwnerPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReviewsRoute = OwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSecurityRoute = OwnerSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSellingRoute = OwnerSellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSlidesRoute = OwnerSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSocialRoute = OwnerSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerUsersRoute = OwnerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerVendorsRoute = OwnerVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerVisitorsRoute = OwnerVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => OwnerRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay/webhook',
  path: '/api/razorpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBillsIndexRoute = OwnerBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsIdRoute = OwnerBillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsExpensesRoute = OwnerBillsExpensesRouteImport.update({
  id: '/bills/expenses',
  path: '/bills/expenses',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsPurchaseRoute = OwnerBillsPurchaseRouteImport.update({
  id: '/bills/purchase',
  path: '/bills/purchase',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsRepairRoute = OwnerBillsRepairRouteImport.update({
  id: '/bills/repair',
  path: '/bills/repair',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsReturnsRoute = OwnerBillsReturnsRouteImport.update({
  id: '/bills/returns',
  path: '/bills/returns',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsSaleRoute = OwnerBillsSaleRouteImport.update({
  id: '/bills/sale',
  path: '/bills/sale',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBillsStockRoute = OwnerBillsStockRouteImport.update({
  id: '/bills/stock',
  path: '/bills/stock',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryIndexRoute = OwnerInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryAlertsRoute = OwnerInventoryAlertsRouteImport.update({
  id: '/inventory/alerts',
  path: '/inventory/alerts',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryLabelsRoute = OwnerInventoryLabelsRouteImport.update({
  id: '/inventory/labels',
  path: '/inventory/labels',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryLedgerRoute = OwnerInventoryLedgerRouteImport.update({
  id: '/inventory/ledger',
  path: '/inventory/ledger',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryScanRoute = OwnerInventoryScanRouteImport.update({
  id: '/inventory/scan',
  path: '/inventory/scan',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryStockRoute = OwnerInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/astrology': typeof AstrologyRoute
  '/brass': typeof BrassRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/colours': typeof ColoursRoute
  '/contact': typeof ContactRoute
  '/copper': typeof CopperRoute
  '/enquire': typeof EnquireRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/navratna': typeof NavratnaRoute
  '/owner': typeof OwnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/shipping': typeof ShippingRoute
  '/track': typeof TrackRoute
  '/why-us': typeof WhyUsRoute
  '/gemstones/$slug': typeof GemstonesSlugRoute
  '/order/$code': typeof OrderCodeRoute
  '/owner/ads': typeof OwnerAdsRoute
  '/owner/appearance': typeof OwnerAppearanceRoute
  '/owner/astrology': typeof OwnerAstrologyRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/discounts': typeof OwnerDiscountsRoute
  '/owner/enquiries': typeof OwnerEnquiriesRoute
  '/owner/gst': typeof OwnerGstRoute
  '/owner/live': typeof OwnerLiveRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/print': typeof OwnerPrintRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/security': typeof OwnerSecurityRoute
  '/owner/selling': typeof OwnerSellingRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/slides': typeof OwnerSlidesRoute
  '/owner/social': typeof OwnerSocialRoute
  '/owner/users': typeof OwnerUsersRoute
  '/owner/vendors': typeof OwnerVendorsRoute
  '/owner/visitors': typeof OwnerVisitorsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/gemstones/': typeof GemstonesIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
  '/owner/bills/$id': typeof OwnerBillsIdRoute
  '/owner/bills/expenses': typeof OwnerBillsExpensesRoute
  '/owner/bills/purchase': typeof OwnerBillsPurchaseRoute
  '/owner/bills/repair': typeof OwnerBillsRepairRoute
  '/owner/bills/returns': typeof OwnerBillsReturnsRoute
  '/owner/bills/sale': typeof OwnerBillsSaleRoute
  '/owner/bills/stock': typeof OwnerBillsStockRoute
  '/owner/inventory/alerts': typeof OwnerInventoryAlertsRoute
  '/owner/inventory/labels': typeof OwnerInventoryLabelsRoute
  '/owner/inventory/ledger': typeof OwnerInventoryLedgerRoute
  '/owner/inventory/scan': typeof OwnerInventoryScanRoute
  '/owner/inventory/stock': typeof OwnerInventoryStockRoute
  '/owner/bills/': typeof OwnerBillsIndexRoute
  '/owner/inventory/': typeof OwnerInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/astrology': typeof AstrologyRoute
  '/brass': typeof BrassRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/colours': typeof ColoursRoute
  '/contact': typeof ContactRoute
  '/copper': typeof CopperRoute
  '/enquire': typeof EnquireRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/navratna': typeof NavratnaRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/shipping': typeof ShippingRoute
  '/track': typeof TrackRoute
  '/why-us': typeof WhyUsRoute
  '/gemstones/$slug': typeof GemstonesSlugRoute
  '/order/$code': typeof OrderCodeRoute
  '/owner/ads': typeof OwnerAdsRoute
  '/owner/appearance': typeof OwnerAppearanceRoute
  '/owner/astrology': typeof OwnerAstrologyRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/discounts': typeof OwnerDiscountsRoute
  '/owner/enquiries': typeof OwnerEnquiriesRoute
  '/owner/gst': typeof OwnerGstRoute
  '/owner/live': typeof OwnerLiveRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/print': typeof OwnerPrintRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/security': typeof OwnerSecurityRoute
  '/owner/selling': typeof OwnerSellingRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/slides': typeof OwnerSlidesRoute
  '/owner/social': typeof OwnerSocialRoute
  '/owner/users': typeof OwnerUsersRoute
  '/owner/vendors': typeof OwnerVendorsRoute
  '/owner/visitors': typeof OwnerVisitorsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/gemstones': typeof GemstonesIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
  '/owner/bills/$id': typeof OwnerBillsIdRoute
  '/owner/bills/expenses': typeof OwnerBillsExpensesRoute
  '/owner/bills/purchase': typeof OwnerBillsPurchaseRoute
  '/owner/bills/repair': typeof OwnerBillsRepairRoute
  '/owner/bills/returns': typeof OwnerBillsReturnsRoute
  '/owner/bills/sale': typeof OwnerBillsSaleRoute
  '/owner/bills/stock': typeof OwnerBillsStockRoute
  '/owner/inventory/alerts': typeof OwnerInventoryAlertsRoute
  '/owner/inventory/labels': typeof OwnerInventoryLabelsRoute
  '/owner/inventory/ledger': typeof OwnerInventoryLedgerRoute
  '/owner/inventory/scan': typeof OwnerInventoryScanRoute
  '/owner/inventory/stock': typeof OwnerInventoryStockRoute
  '/owner/bills': typeof OwnerBillsIndexRoute
  '/owner/inventory': typeof OwnerInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/astrology': typeof AstrologyRoute
  '/brass': typeof BrassRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/colours': typeof ColoursRoute
  '/contact': typeof ContactRoute
  '/copper': typeof CopperRoute
  '/enquire': typeof EnquireRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/navratna': typeof NavratnaRoute
  '/owner': typeof OwnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/shipping': typeof ShippingRoute
  '/track': typeof TrackRoute
  '/why-us': typeof WhyUsRoute
  '/gemstones/$slug': typeof GemstonesSlugRoute
  '/order/$code': typeof OrderCodeRoute
  '/owner/ads': typeof OwnerAdsRoute
  '/owner/appearance': typeof OwnerAppearanceRoute
  '/owner/astrology': typeof OwnerAstrologyRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/discounts': typeof OwnerDiscountsRoute
  '/owner/enquiries': typeof OwnerEnquiriesRoute
  '/owner/gst': typeof OwnerGstRoute
  '/owner/live': typeof OwnerLiveRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/print': typeof OwnerPrintRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/security': typeof OwnerSecurityRoute
  '/owner/selling': typeof OwnerSellingRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/slides': typeof OwnerSlidesRoute
  '/owner/social': typeof OwnerSocialRoute
  '/owner/users': typeof OwnerUsersRoute
  '/owner/vendors': typeof OwnerVendorsRoute
  '/owner/visitors': typeof OwnerVisitorsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/gemstones/': typeof GemstonesIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
  '/owner/bills/$id': typeof OwnerBillsIdRoute
  '/owner/bills/expenses': typeof OwnerBillsExpensesRoute
  '/owner/bills/purchase': typeof OwnerBillsPurchaseRoute
  '/owner/bills/repair': typeof OwnerBillsRepairRoute
  '/owner/bills/returns': typeof OwnerBillsReturnsRoute
  '/owner/bills/sale': typeof OwnerBillsSaleRoute
  '/owner/bills/stock': typeof OwnerBillsStockRoute
  '/owner/inventory/alerts': typeof OwnerInventoryAlertsRoute
  '/owner/inventory/labels': typeof OwnerInventoryLabelsRoute
  '/owner/inventory/ledger': typeof OwnerInventoryLedgerRoute
  '/owner/inventory/scan': typeof OwnerInventoryScanRoute
  '/owner/inventory/stock': typeof OwnerInventoryStockRoute
  '/owner/bills/': typeof OwnerBillsIndexRoute
  '/owner/inventory/': typeof OwnerInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/admin'
    | '/astrology'
    | '/brass'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/colours'
    | '/contact'
    | '/copper'
    | '/enquire'
    | '/history'
    | '/login'
    | '/navratna'
    | '/owner'
    | '/privacy'
    | '/reviews'
    | '/shipping'
    | '/track'
    | '/why-us'
    | '/gemstones/$slug'
    | '/order/$code'
    | '/owner/ads'
    | '/owner/appearance'
    | '/owner/astrology'
    | '/owner/categories'
    | '/owner/discounts'
    | '/owner/enquiries'
    | '/owner/gst'
    | '/owner/live'
    | '/owner/orders'
    | '/owner/payments'
    | '/owner/performance'
    | '/owner/print'
    | '/owner/products'
    | '/owner/reviews'
    | '/owner/security'
    | '/owner/selling'
    | '/owner/settings'
    | '/owner/slides'
    | '/owner/social'
    | '/owner/users'
    | '/owner/vendors'
    | '/owner/visitors'
    | '/shop/$slug'
    | '/gemstones/'
    | '/owner/'
    | '/shop/'
    | '/api/auth/$'
    | '/api/razorpay/webhook'
    | '/owner/bills/$id'
    | '/owner/bills/expenses'
    | '/owner/bills/purchase'
    | '/owner/bills/repair'
    | '/owner/bills/returns'
    | '/owner/bills/sale'
    | '/owner/bills/stock'
    | '/owner/inventory/alerts'
    | '/owner/inventory/labels'
    | '/owner/inventory/ledger'
    | '/owner/inventory/scan'
    | '/owner/inventory/stock'
    | '/owner/bills/'
    | '/owner/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/admin'
    | '/astrology'
    | '/brass'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/colours'
    | '/contact'
    | '/copper'
    | '/enquire'
    | '/history'
    | '/login'
    | '/navratna'
    | '/privacy'
    | '/reviews'
    | '/shipping'
    | '/track'
    | '/why-us'
    | '/gemstones/$slug'
    | '/order/$code'
    | '/owner/ads'
    | '/owner/appearance'
    | '/owner/astrology'
    | '/owner/categories'
    | '/owner/discounts'
    | '/owner/enquiries'
    | '/owner/gst'
    | '/owner/live'
    | '/owner/orders'
    | '/owner/payments'
    | '/owner/performance'
    | '/owner/print'
    | '/owner/products'
    | '/owner/reviews'
    | '/owner/security'
    | '/owner/selling'
    | '/owner/settings'
    | '/owner/slides'
    | '/owner/social'
    | '/owner/users'
    | '/owner/vendors'
    | '/owner/visitors'
    | '/shop/$slug'
    | '/gemstones'
    | '/owner'
    | '/shop'
    | '/api/auth/$'
    | '/api/razorpay/webhook'
    | '/owner/bills/$id'
    | '/owner/bills/expenses'
    | '/owner/bills/purchase'
    | '/owner/bills/repair'
    | '/owner/bills/returns'
    | '/owner/bills/sale'
    | '/owner/bills/stock'
    | '/owner/inventory/alerts'
    | '/owner/inventory/labels'
    | '/owner/inventory/ledger'
    | '/owner/inventory/scan'
    | '/owner/inventory/stock'
    | '/owner/bills'
    | '/owner/inventory'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/admin'
    | '/astrology'
    | '/brass'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/colours'
    | '/contact'
    | '/copper'
    | '/enquire'
    | '/history'
    | '/login'
    | '/navratna'
    | '/owner'
    | '/privacy'
    | '/reviews'
    | '/shipping'
    | '/track'
    | '/why-us'
    | '/gemstones/$slug'
    | '/order/$code'
    | '/owner/ads'
    | '/owner/appearance'
    | '/owner/astrology'
    | '/owner/categories'
    | '/owner/discounts'
    | '/owner/enquiries'
    | '/owner/gst'
    | '/owner/live'
    | '/owner/orders'
    | '/owner/payments'
    | '/owner/performance'
    | '/owner/print'
    | '/owner/products'
    | '/owner/reviews'
    | '/owner/security'
    | '/owner/selling'
    | '/owner/settings'
    | '/owner/slides'
    | '/owner/social'
    | '/owner/users'
    | '/owner/vendors'
    | '/owner/visitors'
    | '/shop/$slug'
    | '/gemstones/'
    | '/owner/'
    | '/shop/'
    | '/api/auth/$'
    | '/api/razorpay/webhook'
    | '/owner/bills/$id'
    | '/owner/bills/expenses'
    | '/owner/bills/purchase'
    | '/owner/bills/repair'
    | '/owner/bills/returns'
    | '/owner/bills/sale'
    | '/owner/bills/stock'
    | '/owner/inventory/alerts'
    | '/owner/inventory/labels'
    | '/owner/inventory/ledger'
    | '/owner/inventory/scan'
    | '/owner/inventory/stock'
    | '/owner/bills/'
    | '/owner/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AstrologyRoute: typeof AstrologyRoute
  BrassRoute: typeof BrassRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ColoursRoute: typeof ColoursRoute
  ContactRoute: typeof ContactRoute
  CopperRoute: typeof CopperRoute
  EnquireRoute: typeof EnquireRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NavratnaRoute: typeof NavratnaRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  ShippingRoute: typeof ShippingRoute
  TrackRoute: typeof TrackRoute
  WhyUsRoute: typeof WhyUsRoute
  GemstonesSlugRoute: typeof GemstonesSlugRoute
  OrderCodeRoute: typeof OrderCodeRoute
  ShopSlugRoute: typeof ShopSlugRoute
  GemstonesIndexRoute: typeof GemstonesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brass': {
      id: '/brass'
      path: '/brass'
      fullPath: '/brass'
      preLoaderRoute: typeof BrassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colours': {
      id: '/colours'
      path: '/colours'
      fullPath: '/colours'
      preLoaderRoute: typeof ColoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copper': {
      id: '/copper'
      path: '/copper'
      fullPath: '/copper'
      preLoaderRoute: typeof CopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navratna': {
      id: '/navratna'
      path: '/navratna'
      fullPath: '/navratna'
      preLoaderRoute: typeof NavratnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemstones/': {
      id: '/gemstones/'
      path: '/gemstones'
      fullPath: '/gemstones/'
      preLoaderRoute: typeof GemstonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemstones/$slug': {
      id: '/gemstones/$slug'
      path: '/gemstones/$slug'
      fullPath: '/gemstones/$slug'
      preLoaderRoute: typeof GemstonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/ads': {
      id: '/owner/ads'
      path: '/ads'
      fullPath: '/owner/ads'
      preLoaderRoute: typeof OwnerAdsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/appearance': {
      id: '/owner/appearance'
      path: '/appearance'
      fullPath: '/owner/appearance'
      preLoaderRoute: typeof OwnerAppearanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/astrology': {
      id: '/owner/astrology'
      path: '/astrology'
      fullPath: '/owner/astrology'
      preLoaderRoute: typeof OwnerAstrologyRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/categories': {
      id: '/owner/categories'
      path: '/categories'
      fullPath: '/owner/categories'
      preLoaderRoute: typeof OwnerCategoriesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/discounts': {
      id: '/owner/discounts'
      path: '/discounts'
      fullPath: '/owner/discounts'
      preLoaderRoute: typeof OwnerDiscountsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/enquiries': {
      id: '/owner/enquiries'
      path: '/enquiries'
      fullPath: '/owner/enquiries'
      preLoaderRoute: typeof OwnerEnquiriesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/gst': {
      id: '/owner/gst'
      path: '/gst'
      fullPath: '/owner/gst'
      preLoaderRoute: typeof OwnerGstRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/live': {
      id: '/owner/live'
      path: '/live'
      fullPath: '/owner/live'
      preLoaderRoute: typeof OwnerLiveRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/payments': {
      id: '/owner/payments'
      path: '/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof OwnerPaymentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/performance': {
      id: '/owner/performance'
      path: '/performance'
      fullPath: '/owner/performance'
      preLoaderRoute: typeof OwnerPerformanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/print': {
      id: '/owner/print'
      path: '/print'
      fullPath: '/owner/print'
      preLoaderRoute: typeof OwnerPrintRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/products': {
      id: '/owner/products'
      path: '/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reviews': {
      id: '/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof OwnerReviewsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/security': {
      id: '/owner/security'
      path: '/security'
      fullPath: '/owner/security'
      preLoaderRoute: typeof OwnerSecurityRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/selling': {
      id: '/owner/selling'
      path: '/selling'
      fullPath: '/owner/selling'
      preLoaderRoute: typeof OwnerSellingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/slides': {
      id: '/owner/slides'
      path: '/slides'
      fullPath: '/owner/slides'
      preLoaderRoute: typeof OwnerSlidesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/social': {
      id: '/owner/social'
      path: '/social'
      fullPath: '/owner/social'
      preLoaderRoute: typeof OwnerSocialRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/users': {
      id: '/owner/users'
      path: '/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof OwnerUsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/vendors': {
      id: '/owner/vendors'
      path: '/vendors'
      fullPath: '/owner/vendors'
      preLoaderRoute: typeof OwnerVendorsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/visitors': {
      id: '/owner/visitors'
      path: '/visitors'
      fullPath: '/owner/visitors'
      preLoaderRoute: typeof OwnerVisitorsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/webhook': {
      id: '/api/razorpay/webhook'
      path: '/api/razorpay/webhook'
      fullPath: '/api/razorpay/webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bills/': {
      id: '/owner/bills/'
      path: '/bills'
      fullPath: '/owner/bills/'
      preLoaderRoute: typeof OwnerBillsIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/$id': {
      id: '/owner/bills/$id'
      path: '/bills/$id'
      fullPath: '/owner/bills/$id'
      preLoaderRoute: typeof OwnerBillsIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/expenses': {
      id: '/owner/bills/expenses'
      path: '/bills/expenses'
      fullPath: '/owner/bills/expenses'
      preLoaderRoute: typeof OwnerBillsExpensesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/purchase': {
      id: '/owner/bills/purchase'
      path: '/bills/purchase'
      fullPath: '/owner/bills/purchase'
      preLoaderRoute: typeof OwnerBillsPurchaseRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/repair': {
      id: '/owner/bills/repair'
      path: '/bills/repair'
      fullPath: '/owner/bills/repair'
      preLoaderRoute: typeof OwnerBillsRepairRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/returns': {
      id: '/owner/bills/returns'
      path: '/bills/returns'
      fullPath: '/owner/bills/returns'
      preLoaderRoute: typeof OwnerBillsReturnsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/sale': {
      id: '/owner/bills/sale'
      path: '/bills/sale'
      fullPath: '/owner/bills/sale'
      preLoaderRoute: typeof OwnerBillsSaleRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bills/stock': {
      id: '/owner/bills/stock'
      path: '/bills/stock'
      fullPath: '/owner/bills/stock'
      preLoaderRoute: typeof OwnerBillsStockRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory/': {
      id: '/owner/inventory/'
      path: '/inventory'
      fullPath: '/owner/inventory/'
      preLoaderRoute: typeof OwnerInventoryIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory/alerts': {
      id: '/owner/inventory/alerts'
      path: '/inventory/alerts'
      fullPath: '/owner/inventory/alerts'
      preLoaderRoute: typeof OwnerInventoryAlertsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory/labels': {
      id: '/owner/inventory/labels'
      path: '/inventory/labels'
      fullPath: '/owner/inventory/labels'
      preLoaderRoute: typeof OwnerInventoryLabelsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory/ledger': {
      id: '/owner/inventory/ledger'
      path: '/inventory/ledger'
      fullPath: '/owner/inventory/ledger'
      preLoaderRoute: typeof OwnerInventoryLedgerRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory/scan': {
      id: '/owner/inventory/scan'
      path: '/inventory/scan'
      fullPath: '/owner/inventory/scan'
      preLoaderRoute: typeof OwnerInventoryScanRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory/stock': {
      id: '/owner/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/owner/inventory/stock'
      preLoaderRoute: typeof OwnerInventoryStockRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerAdsRoute: typeof OwnerAdsRoute
  OwnerAppearanceRoute: typeof OwnerAppearanceRoute
  OwnerAstrologyRoute: typeof OwnerAstrologyRoute
  OwnerCategoriesRoute: typeof OwnerCategoriesRoute
  OwnerDiscountsRoute: typeof OwnerDiscountsRoute
  OwnerEnquiriesRoute: typeof OwnerEnquiriesRoute
  OwnerGstRoute: typeof OwnerGstRoute
  OwnerLiveRoute: typeof OwnerLiveRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerPaymentsRoute: typeof OwnerPaymentsRoute
  OwnerPerformanceRoute: typeof OwnerPerformanceRoute
  OwnerPrintRoute: typeof OwnerPrintRoute
  OwnerProductsRoute: typeof OwnerProductsRoute
  OwnerReviewsRoute: typeof OwnerReviewsRoute
  OwnerSecurityRoute: typeof OwnerSecurityRoute
  OwnerSellingRoute: typeof OwnerSellingRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerSlidesRoute: typeof OwnerSlidesRoute
  OwnerSocialRoute: typeof OwnerSocialRoute
  OwnerUsersRoute: typeof OwnerUsersRoute
  OwnerVendorsRoute: typeof OwnerVendorsRoute
  OwnerVisitorsRoute: typeof OwnerVisitorsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerBillsIdRoute: typeof OwnerBillsIdRoute
  OwnerBillsExpensesRoute: typeof OwnerBillsExpensesRoute
  OwnerBillsPurchaseRoute: typeof OwnerBillsPurchaseRoute
  OwnerBillsRepairRoute: typeof OwnerBillsRepairRoute
  OwnerBillsReturnsRoute: typeof OwnerBillsReturnsRoute
  OwnerBillsSaleRoute: typeof OwnerBillsSaleRoute
  OwnerBillsStockRoute: typeof OwnerBillsStockRoute
  OwnerInventoryAlertsRoute: typeof OwnerInventoryAlertsRoute
  OwnerInventoryLabelsRoute: typeof OwnerInventoryLabelsRoute
  OwnerInventoryLedgerRoute: typeof OwnerInventoryLedgerRoute
  OwnerInventoryScanRoute: typeof OwnerInventoryScanRoute
  OwnerInventoryStockRoute: typeof OwnerInventoryStockRoute
  OwnerBillsIndexRoute: typeof OwnerBillsIndexRoute
  OwnerInventoryIndexRoute: typeof OwnerInventoryIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAdsRoute: OwnerAdsRoute,
  OwnerAppearanceRoute: OwnerAppearanceRoute,
  OwnerAstrologyRoute: OwnerAstrologyRoute,
  OwnerCategoriesRoute: OwnerCategoriesRoute,
  OwnerDiscountsRoute: OwnerDiscountsRoute,
  OwnerEnquiriesRoute: OwnerEnquiriesRoute,
  OwnerGstRoute: OwnerGstRoute,
  OwnerLiveRoute: OwnerLiveRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerPerformanceRoute: OwnerPerformanceRoute,
  OwnerPrintRoute: OwnerPrintRoute,
  OwnerProductsRoute: OwnerProductsRoute,
  OwnerReviewsRoute: OwnerReviewsRoute,
  OwnerSecurityRoute: OwnerSecurityRoute,
  OwnerSellingRoute: OwnerSellingRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerSlidesRoute: OwnerSlidesRoute,
  OwnerSocialRoute: OwnerSocialRoute,
  OwnerUsersRoute: OwnerUsersRoute,
  OwnerVendorsRoute: OwnerVendorsRoute,
  OwnerVisitorsRoute: OwnerVisitorsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerBillsIdRoute: OwnerBillsIdRoute,
  OwnerBillsExpensesRoute: OwnerBillsExpensesRoute,
  OwnerBillsPurchaseRoute: OwnerBillsPurchaseRoute,
  OwnerBillsRepairRoute: OwnerBillsRepairRoute,
  OwnerBillsReturnsRoute: OwnerBillsReturnsRoute,
  OwnerBillsSaleRoute: OwnerBillsSaleRoute,
  OwnerBillsStockRoute: OwnerBillsStockRoute,
  OwnerInventoryAlertsRoute: OwnerInventoryAlertsRoute,
  OwnerInventoryLabelsRoute: OwnerInventoryLabelsRoute,
  OwnerInventoryLedgerRoute: OwnerInventoryLedgerRoute,
  OwnerInventoryScanRoute: OwnerInventoryScanRoute,
  OwnerInventoryStockRoute: OwnerInventoryStockRoute,
  OwnerBillsIndexRoute: OwnerBillsIndexRoute,
  OwnerInventoryIndexRoute: OwnerInventoryIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AstrologyRoute: AstrologyRoute,
  BrassRoute: BrassRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ColoursRoute: ColoursRoute,
  ContactRoute: ContactRoute,
  CopperRoute: CopperRoute,
  EnquireRoute: EnquireRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NavratnaRoute: NavratnaRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  ShippingRoute: ShippingRoute,
  TrackRoute: TrackRoute,
  WhyUsRoute: WhyUsRoute,
  GemstonesSlugRoute: GemstonesSlugRoute,
  OrderCodeRoute: OrderCodeRoute,
  ShopSlugRoute: ShopSlugRoute,
  GemstonesIndexRoute: GemstonesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
